{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/evil-pkg2/MAL-2025-2961.json"
      },
      "package": {
        "ecosystem": "PyPI",
        "name": "evil-pkg2",
        "purl": "pkg:pypi/evil-pkg2"
      },
      "versions": [
        "0.2",
        "0.3"
      ]
    }
  ],
  "credits": [
    {
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "name": "ReversingLabs",
      "type": "FINDER"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-01959",
        "import_time": "2025-03-31T07:07:05.516676221Z",
        "modified_time": "2025-03-28T13:05:38Z",
        "sha256": "374453a4f6e085b592f8b244146b4f1f6f3ff6be667d4cb49f4cc89a72756c66",
        "source": "reversing-labs",
        "versions": [
          "0.2",
          "0.3"
        ]
      }
    ]
  },
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "id": "MAL-2025-2961",
  "modified": "2025-03-28T13:05:38Z",
  "published": "2025-03-28T13:05:38Z",
  "schema_version": "1.7.3",
  "summary": "Malicious code in evil-pkg2 (PyPI)"
}