{
  "id": "MAL-2024-5709",
  "summary": "Malicious code in pyfontingpkgv1 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-PYFONTINGPKGV1-5932217"
  ],
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:40:02Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "sha256": "70634ffad4604fdb9b13a71d0adc2fc5c26396d066611458ff06e42ec844a42c",
        "import_time": "2024-06-28T02:50:06.675520344Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04493",
        "source": "reversing-labs",
        "modified_time": "2024-06-25T13:40:02Z"
      },
      {
        "sha256": "d0a0a40a1e286479adffd3d087350ce2ba9b34771ec6693b7dba8f1ca417753e",
        "import_time": "2024-10-24T00:59:51.236059685Z",
        "id": "RLUA-2024-08931",
        "source": "reversing-labs",
        "modified_time": "2024-10-16T14:47:58Z"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYFONTINGPKGV1-5932217"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pyfontingpkgv1",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pyfontingpkgv1"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyfontingpkgv1/MAL-2024-5709.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}