{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2019/UBUNTU-CVE-2019-14853.json"
      },
      "ecosystem_specific": {
        "availability": "No subscription required",
        "binaries": [
          {
            "binary_name": "python-ecdsa",
            "binary_version": "0.13-2ubuntu0.16.04.1"
          },
          {
            "binary_name": "python3-ecdsa",
            "binary_version": "0.13-2ubuntu0.16.04.1"
          }
        ],
        "ubuntu_priority": "low"
      },
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS",
        "name": "python-ecdsa",
        "purl": "pkg:deb/ubuntu/python-ecdsa@0.13-2ubuntu0.16.04.1?arch=source&distro=xenial"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.13-2ubuntu0.16.04.1"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "0.13-2"
      ]
    },
    {
      "database_specific": {
        "source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2019/UBUNTU-CVE-2019-14853.json"
      },
      "ecosystem_specific": {
        "availability": "No subscription required",
        "binaries": [
          {
            "binary_name": "python-ecdsa",
            "binary_version": "0.13-2ubuntu0.18.04.1"
          },
          {
            "binary_name": "python3-ecdsa",
            "binary_version": "0.13-2ubuntu0.18.04.1"
          }
        ],
        "ubuntu_priority": "low"
      },
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-ecdsa",
        "purl": "pkg:deb/ubuntu/python-ecdsa@0.13-2ubuntu0.18.04.1?arch=source&distro=bionic"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.13-2ubuntu0.18.04.1"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "0.13-2"
      ]
    }
  ],
  "details": "An error-handling flaw was found in python-ecdsa before version 0.13.3. During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service.",
  "id": "UBUNTU-CVE-2019-14853",
  "modified": "2025-06-02T17:10:29Z",
  "published": "2019-10-14T00:00:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2019-14853"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/warner/python-ecdsa/pull/115"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/warner/python-ecdsa/pull/124"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-4196-1"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2019-14853"
    }
  ],
  "related": [
    "CVE-2019-14853",
    "USN-4196-1"
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "type": "CVSS_V3"
    },
    {
      "score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "type": "CVSS_V3"
    }
  ]
}